name: Build

on:
  push:
    branches: [ "main", "prod" ]
  pull_request:
    branches: [ "main", "prod" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.1.0
      with:
        node-version: '23'

    - name: Install and Build Frontend Dependencies
      run: |
        cd frontend
        npm install
        npm run build
      env:
        CI: false

    - name: Return to root directory
      run: cd ..

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install Go dependencies
      run: go get .

    - name: Build backend
      run: go build -v >> logs

    - name: Upload Go Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: 'logs'
        path: 'logs'