# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.1.0
      with:
        node-version: '23'

    - name: Setup npm packages
      run: npm install

    - name: Set up the frontend in react
      run: npm run build
      env:
        CI: false

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up Go Sqlite3
      run: go get .

    - name: Build
      run: go build -v >> logs

    - name: Upload Go Build Result
      uses: actions/upload-artifact@v4
      with:
        name: 'logs'
        path: 'logs'
